version: '3.9'

services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env_prod
    depends_on:
      - db
    command: flask run

  db:
    platform: linux/amd64
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: seeds_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
